### ISSUE TITLE
On Mac Android Studio freezes when right-clicking Project files

### ISSUE THREAD

**Issue by ebelevics** [NicolaVerbeeck/drift_local_storage_inspector#1]
I have this issue on Macbook Pro M1 using Android Studio Bumblebee
Without Local Storage Inspector plugin everything works fine and on right-click I get this window instantly:
<img width="331" alt="Screenshot 2022-07-25 at 10 13 16" src="https://user-images.githubusercontent.com/25333580/180719809-538262af-1263-46cc-8ef2-d48b24001038.png">

When I do enable Local Storage Inspector plugin, on right-click I have to wait about 30-60 seconds to open much larger options
![image](https://user-images.githubusercontent.com/25333580/180720059-ef1e3aff-61eb-4d68-a481-dc8083e94fd5.png)

Well I it's not possible to work like this, when on every right-click Android Studio freezes for 30-60 seconds because of plugin.

**Comment by NicolaVerbeeck** [comment]
Strange, is this on any file you right click?

**Comment by ebelevics** [comment]
yes

**Comment by NicolaVerbeeck** [comment]
Very strange as I cannot reproduce this issue at all on chipmunk and above. I will try to find some time to check bumblebee but as far as I can tell there is no reason/code for this plugin to interact with the menu at all.

**Comment by ebelevics** [comment]
Ok, I'll try to update Android Studio, hope this will resolve issue

**Comment by ebelevics** [comment]
Still the same. Only now I get indicator that something is happening, but still have to wait alot.
<img width="158" alt="image" src="https://user-images.githubusercontent.com/25333580/180726321-9aa91a05-2ba6-4cbb-ab24-eba0040e1665.png">

**Comment by NicolaVerbeeck** [comment]
Do you have any other non-standard plugins enabled?

This could be an apple-silicon related issue. Unfortunately I don't have an apple-silicon device at this time

**Comment by ebelevics** [comment]
I'll try enabling/disabling other plugins, creating clean flutter project. In worst case scenario install Android Studio with Intel. Will tell you about results.

**Comment by ebelevics** [comment]
Ok, thank you! It seems that this plugin interaction with SQLDelight (plugin) caused some problems. I've disabled SQLDelight and now it seems everything works as expected.

**Comment by NicolaVerbeeck** [comment]
Yeah this plugin uses a part of SQLDelight to do syntax highlighting in the query part. This _should_ be fixed in the intellij 2022 variant releases, if it is not I will have to do more investigation. 

Thanks for the report!
