### ISSUE TITLE
SQLDataType _makeType( should not return null

### ISSUE THREAD

**Issue by mikemoore13** [NicolaVerbeeck/drift_local_storage_inspector#3]
error on windows you should add the   return SQLDataType.text; as a default value else it complains it returns null
the compiler will bloc else 

SQLDataType _makeType(
  GeneratedColumn<dynamic> column,
) {
  final type = column.type;
  switch (type) {
    case DriftSqlType.bool:
      return SQLDataType.boolean;
    case DriftSqlType.string:
      return SQLDataType.text;
    case DriftSqlType.bigInt:
      return SQLDataType.integer;
    case DriftSqlType.int:
      return SQLDataType.integer;
    case DriftSqlType.dateTime:
      return SQLDataType.datetime;
    case DriftSqlType.blob:
      return SQLDataType.blob;
    case DriftSqlType.double:
      return SQLDataType.real;
  }
  return SQLDataType.text;
}

**Comment by NicolaVerbeeck** [comment]
Support for drift 2.4.0 has been added in version 0.5.0
