### ISSUE TITLE
not build after update

### ISSUE THREAD

**Issue by ohari5336** [NicolaVerbeeck/drift_local_storage_inspector#6]
SQLDataType _makeType(
  GeneratedColumn<dynamic> column,
) {
  final type = column.type as DriftSqlType; <<<< Fixed By Adding This
  switch (type) {
    case DriftSqlType.bool:
      return SQLDataType.boolean;
    case DriftSqlType.string:
      return SQLDataType.text;
    case DriftSqlType.bigInt:
      return SQLDataType.integer;
    case DriftSqlType.int:
      return SQLDataType.integer;
    case DriftSqlType.dateTime:
      return SQLDataType.datetime;
    case DriftSqlType.blob:
      return SQLDataType.blob;
    case DriftSqlType.double:
      return SQLDataType.real;
    case DriftSqlType.any:
      return SQLDataType.text;
  }
}

**Comment by NicolaVerbeeck** [comment]
I know there are some incompatibilities with the update and I am trying to attend them ASAP. But with work, covid,...

**Comment by NicolaVerbeeck** [comment]
This should be resolved in release 0.7.0
