### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by jack24254029** [NicolaVerbeeck/drift_local_storage_inspector#8]
I follow the READEME.md to setting this.

I think code was fine, but I couldn't see my device in the local storage inspector of Inteilj Plugin.

[I asked the question to local storage inspector's author, but I didn't recieve the feedback.](https://github.com/NicolaVerbeeck/flutter_local_storage_inspector/issues/24)

It was work before I changed the Intel mac to M2 mac.

**Comment by NicolaVerbeeck** [comment]
This seems to be an issue specific to your device. Without such a machine or your configuration it is very hard to debug what specifically does not work. Lets continue this conversation on the other ticket.

Please keep in mind that this is all provided free of charge and my time is not unlimited

**Comment by jack24254029** [comment]
Thank you very much.
